/*
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AlertModification model module.
 * @module model/AlertModification
 * @version 3.0
 */
export class AlertModification {
  /**
   * Constructs a new <code>AlertModification</code>.
   * @alias module:model/AlertModification
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AlertModification</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AlertModification} obj Optional instance to populate.
   * @return {module:model/AlertModification} The populated <code>AlertModification</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AlertModification();
      if (data.hasOwnProperty('lastActionIndex'))
        obj.lastActionIndex = ApiClient.convertToType(data['lastActionIndex'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} lastActionIndex
 */
AlertModification.prototype.lastActionIndex = undefined;

