/*
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Alert} from './Alert';
import {V2RegionType} from './V2RegionType';

/**
 * The AlertRegionModel model module.
 * @module model/AlertRegionModel
 * @version 3.0
 */
export class AlertRegionModel {
  /**
   * Constructs a new <code>AlertRegionModel</code>.
   * @alias module:model/AlertRegionModel
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AlertRegionModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AlertRegionModel} obj Optional instance to populate.
   * @return {module:model/AlertRegionModel} The populated <code>AlertRegionModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AlertRegionModel();
      if (data.hasOwnProperty('regionId'))
        obj.regionId = ApiClient.convertToType(data['regionId'], 'String');
      if (data.hasOwnProperty('regionType'))
        obj.regionType = V2RegionType.constructFromObject(data['regionType']);
      if (data.hasOwnProperty('regionName'))
        obj.regionName = ApiClient.convertToType(data['regionName'], 'String');
      if (data.hasOwnProperty('regionEngName'))
        obj.regionEngName = ApiClient.convertToType(data['regionEngName'], 'String');
      if (data.hasOwnProperty('lastUpdate'))
        obj.lastUpdate = ApiClient.convertToType(data['lastUpdate'], 'Date');
      if (data.hasOwnProperty('activeAlerts'))
        obj.activeAlerts = ApiClient.convertToType(data['activeAlerts'], [Alert]);
    }
    return obj;
  }
}

/**
 * @member {String} regionId
 */
AlertRegionModel.prototype.regionId = undefined;

/**
 * @member {module:model/V2RegionType} regionType
 */
AlertRegionModel.prototype.regionType = undefined;

/**
 * @member {String} regionName
 */
AlertRegionModel.prototype.regionName = undefined;

/**
 * @member {String} regionEngName
 */
AlertRegionModel.prototype.regionEngName = undefined;

/**
 * @member {Date} lastUpdate
 */
AlertRegionModel.prototype.lastUpdate = undefined;

/**
 * @member {Array.<module:model/Alert>} activeAlerts
 */
AlertRegionModel.prototype.activeAlerts = undefined;

