/*
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AlertType} from './AlertType';
import {V2RegionType} from './V2RegionType';

/**
 * The Alert model module.
 * @module model/Alert
 * @version 3.0
 */
export class Alert {
  /**
   * Constructs a new <code>Alert</code>.
   * @alias module:model/Alert
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Alert</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Alert} obj Optional instance to populate.
   * @return {module:model/Alert} The populated <code>Alert</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Alert();
      if (data.hasOwnProperty('regionId'))
        obj.regionId = ApiClient.convertToType(data['regionId'], 'String');
      if (data.hasOwnProperty('regionType'))
        obj.regionType = V2RegionType.constructFromObject(data['regionType']);
      if (data.hasOwnProperty('type'))
        obj.type = AlertType.constructFromObject(data['type']);
      if (data.hasOwnProperty('lastUpdate'))
        obj.lastUpdate = ApiClient.convertToType(data['lastUpdate'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {String} regionId
 */
Alert.prototype.regionId = undefined;

/**
 * @member {module:model/V2RegionType} regionType
 */
Alert.prototype.regionType = undefined;

/**
 * @member {module:model/AlertType} type
 */
Alert.prototype.type = undefined;

/**
 * @member {Date} lastUpdate
 */
Alert.prototype.lastUpdate = undefined;

