/*
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class AlertType.
 * @enum {String}
 * @readonly
 */
const AlertType = {
  /**
   * value: "UNKNOWN"
   * @const
   */
  UNKNOWN: "UNKNOWN",

  /**
   * value: "AIR"
   * @const
   */
  AIR: "AIR",

  /**
   * value: "ARTILLERY"
   * @const
   */
  ARTILLERY: "ARTILLERY",

  /**
   * value: "URBAN_FIGHTS"
   * @const
   */
  URBAN_FIGHTS: "URBAN_FIGHTS",

  /**
   * value: "CHEMICAL"
   * @const
   */
  CHEMICAL: "CHEMICAL",

  /**
   * value: "NUCLEAR"
   * @const
   */
  NUCLEAR: "NUCLEAR",

  /**
   * value: "INFO"
   * @const
   */
  INFO: "INFO",

  /**
   * Returns a <code>AlertType</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/AlertType} The enum <code>AlertType</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {AlertType};