/*
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {RegionAlarmModel} from './RegionAlarmModel';

/**
 * The RegionAlarmsHistory model module.
 * @module model/RegionAlarmsHistory
 * @version 3.0
 */
export class RegionAlarmsHistory {
  /**
   * Constructs a new <code>RegionAlarmsHistory</code>.
   * @alias module:model/RegionAlarmsHistory
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RegionAlarmsHistory</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RegionAlarmsHistory} obj Optional instance to populate.
   * @return {module:model/RegionAlarmsHistory} The populated <code>RegionAlarmsHistory</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RegionAlarmsHistory();
      if (data.hasOwnProperty('regionId'))
        obj.regionId = ApiClient.convertToType(data['regionId'], 'String');
      if (data.hasOwnProperty('regionName'))
        obj.regionName = ApiClient.convertToType(data['regionName'], 'String');
      if (data.hasOwnProperty('alarms'))
        obj.alarms = ApiClient.convertToType(data['alarms'], [RegionAlarmModel]);
    }
    return obj;
  }
}

/**
 * @member {String} regionId
 */
RegionAlarmsHistory.prototype.regionId = undefined;

/**
 * @member {String} regionName
 */
RegionAlarmsHistory.prototype.regionName = undefined;

/**
 * @member {Array.<module:model/RegionAlarmModel>} alarms
 */
RegionAlarmsHistory.prototype.alarms = undefined;

