/*
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AlertType} from './AlertType';
import {TimeSpan} from './TimeSpan';

/**
 * The RegionAlarmModel model module.
 * @module model/RegionAlarmModel
 * @version 3.0
 */
export class RegionAlarmModel {
  /**
   * Constructs a new <code>RegionAlarmModel</code>.
   * @alias module:model/RegionAlarmModel
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RegionAlarmModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RegionAlarmModel} obj Optional instance to populate.
   * @return {module:model/RegionAlarmModel} The populated <code>RegionAlarmModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RegionAlarmModel();
      if (data.hasOwnProperty('regionId'))
        obj.regionId = ApiClient.convertToType(data['regionId'], 'String');
      if (data.hasOwnProperty('startDate'))
        obj.startDate = ApiClient.convertToType(data['startDate'], 'Date');
      if (data.hasOwnProperty('endDate'))
        obj.endDate = ApiClient.convertToType(data['endDate'], 'Date');
      if (data.hasOwnProperty('duration'))
        obj.duration = TimeSpan.constructFromObject(data['duration']);
      if (data.hasOwnProperty('alertType'))
        obj.alertType = AlertType.constructFromObject(data['alertType']);
      if (data.hasOwnProperty('regionName'))
        obj.regionName = ApiClient.convertToType(data['regionName'], 'String');
      if (data.hasOwnProperty('isContinue'))
        obj.isContinue = ApiClient.convertToType(data['isContinue'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} regionId
 */
RegionAlarmModel.prototype.regionId = undefined;

/**
 * @member {Date} startDate
 */
RegionAlarmModel.prototype.startDate = undefined;

/**
 * @member {Date} endDate
 */
RegionAlarmModel.prototype.endDate = undefined;

/**
 * @member {module:model/TimeSpan} duration
 */
RegionAlarmModel.prototype.duration = undefined;

/**
 * @member {module:model/AlertType} alertType
 */
RegionAlarmModel.prototype.alertType = undefined;

/**
 * @member {String} regionName
 */
RegionAlarmModel.prototype.regionName = undefined;

/**
 * @member {Boolean} isContinue
 */
RegionAlarmModel.prototype.isContinue = undefined;

