/*
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {V2RegionType} from './V2RegionType';

/**
 * The RegionViewModel model module.
 * @module model/RegionViewModel
 * @version 3.0
 */
export class RegionViewModel {
  /**
   * Constructs a new <code>RegionViewModel</code>.
   * @alias module:model/RegionViewModel
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RegionViewModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RegionViewModel} obj Optional instance to populate.
   * @return {module:model/RegionViewModel} The populated <code>RegionViewModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RegionViewModel();
      if (data.hasOwnProperty('regionId'))
        obj.regionId = ApiClient.convertToType(data['regionId'], 'String');
      if (data.hasOwnProperty('regionName'))
        obj.regionName = ApiClient.convertToType(data['regionName'], 'String');
      if (data.hasOwnProperty('regionType'))
        obj.regionType = V2RegionType.constructFromObject(data['regionType']);
      if (data.hasOwnProperty('regionChildIds'))
        obj.regionChildIds = ApiClient.convertToType(data['regionChildIds'], [RegionViewModel]);
    }
    return obj;
  }
}

/**
 * @member {String} regionId
 */
RegionViewModel.prototype.regionId = undefined;

/**
 * @member {String} regionName
 */
RegionViewModel.prototype.regionName = undefined;

/**
 * @member {module:model/V2RegionType} regionType
 */
RegionViewModel.prototype.regionType = undefined;

/**
 * @member {Array.<module:model/RegionViewModel>} regionChildIds
 */
RegionViewModel.prototype.regionChildIds = undefined;

