/*
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The WebHookModel model module.
 * @module model/WebHookModel
 * @version 3.0
 */
export class WebHookModel {
  /**
   * Constructs a new <code>WebHookModel</code>.
   * @alias module:model/WebHookModel
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>WebHookModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WebHookModel} obj Optional instance to populate.
   * @return {module:model/WebHookModel} The populated <code>WebHookModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WebHookModel();
      if (data.hasOwnProperty('webHookUrl'))
        obj.webHookUrl = ApiClient.convertToType(data['webHookUrl'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} webHookUrl
 */
WebHookModel.prototype.webHookUrl = undefined;

