/*
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {AlertRegionModel} from '../model/AlertRegionModel';
import {WebHookModel} from '../model/WebHookModel';

/**
* WebHook service.
* @module api/WebHookApi
* @version 3.0
*/
export class WebHookApi {

    /**
    * Constructs a new WebHookApi. 
    * @alias module:api/WebHookApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the apiV3WebhookDelete operation.
     * @callback moduleapi/WebHookApi~apiV3WebhookDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Відписка на WebHook про нові сирени та їх відбій
     * @param {Object} opts Optional parameters
     * @param {module:model/WebHookModel} opts.body 
     * @param {module:api/WebHookApi~apiV3WebhookDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiV3WebhookDelete(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Token'];
      let contentTypes = ['application/json', 'text/json', 'application/_*+json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/v3/webhook', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiV3WebhookPatch operation.
     * @callback moduleapi/WebHookApi~apiV3WebhookPatchCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Оновлення WebHook посилання про нові сирени та їх відбій
     * @param {Object} opts Optional parameters
     * @param {module:model/WebHookModel} opts.body 
     * @param {module:api/WebHookApi~apiV3WebhookPatchCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiV3WebhookPatch(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Token'];
      let contentTypes = ['application/json', 'text/json', 'application/_*+json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/v3/webhook', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiV3WebhookPost operation.
     * @callback moduleapi/WebHookApi~apiV3WebhookPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AlertRegionModel{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Підписка на WebHook про нові сирени та їх відбій. У вебхукі відпрявляється подія тривоги/відбою (приклад в відповіді \&quot;200\&quot;)
     * @param {Object} opts Optional parameters
     * @param {module:model/WebHookModel} opts.body 
     * @param {module:api/WebHookApi~apiV3WebhookPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiV3WebhookPost(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Token'];
      let contentTypes = ['application/json', 'text/json', 'application/_*+json'];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = AlertRegionModel;

      return this.apiClient.callApi(
        '/api/v3/webhook', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}