/*
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UkraineAlertApi);
  }
}(this, function(expect, UkraineAlertApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('RegionViewModel', function() {
      beforeEach(function() {
        instance = new UkraineAlertApi.RegionViewModel();
      });

      it('should create an instance of RegionViewModel', function() {
        // TODO: update the code to test RegionViewModel
        expect(instance).to.be.a(UkraineAlertApi.RegionViewModel);
      });

      it('should have the property regionId (base name: "regionId")', function() {
        // TODO: update the code to test the property regionId
        expect(instance).to.have.property('regionId');
        // expect(instance.regionId).to.be(expectedValueLiteral);
      });

      it('should have the property regionName (base name: "regionName")', function() {
        // TODO: update the code to test the property regionName
        expect(instance).to.have.property('regionName');
        // expect(instance.regionName).to.be(expectedValueLiteral);
      });

      it('should have the property regionType (base name: "regionType")', function() {
        // TODO: update the code to test the property regionType
        expect(instance).to.have.property('regionType');
        // expect(instance.regionType).to.be(expectedValueLiteral);
      });

      it('should have the property regionChildIds (base name: "regionChildIds")', function() {
        // TODO: update the code to test the property regionChildIds
        expect(instance).to.have.property('regionChildIds');
        // expect(instance.regionChildIds).to.be(expectedValueLiteral);
      });

    });
  });

}));
