/*
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UkraineAlertApi);
  }
}(this, function(expect, UkraineAlertApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('WebHookModel', function() {
      beforeEach(function() {
        instance = new UkraineAlertApi.WebHookModel();
      });

      it('should create an instance of WebHookModel', function() {
        // TODO: update the code to test WebHookModel
        expect(instance).to.be.a(UkraineAlertApi.WebHookModel);
      });

      it('should have the property webHookUrl (base name: "webHookUrl")', function() {
        // TODO: update the code to test the property webHookUrl
        expect(instance).to.have.property('webHookUrl');
        // expect(instance.webHookUrl).to.be(expectedValueLiteral);
      });

    });
  });

}));
