/*
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {Alert} from './model/Alert';
import {AlertModification} from './model/AlertModification';
import {AlertRegionModel} from './model/AlertRegionModel';
import {AlertType} from './model/AlertType';
import {RegionAlarmModel} from './model/RegionAlarmModel';
import {RegionAlarmsHistory} from './model/RegionAlarmsHistory';
import {RegionViewModel} from './model/RegionViewModel';
import {RegionsViewModel} from './model/RegionsViewModel';
import {TimeSpan} from './model/TimeSpan';
import {V2RegionType} from './model/V2RegionType';
import {WebHookModel} from './model/WebHookModel';
import {AlertsApi} from './api/AlertsApi';
import {RegionsApi} from './api/RegionsApi';
import {WebHookApi} from './api/WebHookApi';

/**
* Object.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var UkraineAlertApi = require('index'); // See note below*.
* var xxxSvc = new UkraineAlertApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new UkraineAlertApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new UkraineAlertApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new UkraineAlertApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 3.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Alert model constructor.
     * @property {module:model/Alert}
     */
    Alert,

    /**
     * The AlertModification model constructor.
     * @property {module:model/AlertModification}
     */
    AlertModification,

    /**
     * The AlertRegionModel model constructor.
     * @property {module:model/AlertRegionModel}
     */
    AlertRegionModel,

    /**
     * The AlertType model constructor.
     * @property {module:model/AlertType}
     */
    AlertType,

    /**
     * The RegionAlarmModel model constructor.
     * @property {module:model/RegionAlarmModel}
     */
    RegionAlarmModel,

    /**
     * The RegionAlarmsHistory model constructor.
     * @property {module:model/RegionAlarmsHistory}
     */
    RegionAlarmsHistory,

    /**
     * The RegionViewModel model constructor.
     * @property {module:model/RegionViewModel}
     */
    RegionViewModel,

    /**
     * The RegionsViewModel model constructor.
     * @property {module:model/RegionsViewModel}
     */
    RegionsViewModel,

    /**
     * The TimeSpan model constructor.
     * @property {module:model/TimeSpan}
     */
    TimeSpan,

    /**
     * The V2RegionType model constructor.
     * @property {module:model/V2RegionType}
     */
    V2RegionType,

    /**
     * The WebHookModel model constructor.
     * @property {module:model/WebHookModel}
     */
    WebHookModel,

    /**
    * The AlertsApi service constructor.
    * @property {module:api/AlertsApi}
    */
    AlertsApi,

    /**
    * The RegionsApi service constructor.
    * @property {module:api/RegionsApi}
    */
    RegionsApi,

    /**
    * The WebHookApi service constructor.
    * @property {module:api/WebHookApi}
    */
    WebHookApi
};
